### ISSUE TITLE
Kanban Board Setup

### ISSUE THREAD

**Issue by awaisanwar544** [awaisanwar544/spacex-project#25]
Link to the project:

https://github.com/awaisanwar544/spacex-project/projects/2

Hello Reviewer,
We are two teammates for this group project.

**Comment by BrianSammit** [comment]
# STATUS: APPROVED :green_circle: :clap: 

Hello @awaisanwar544  and @gdumani, 
Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 

TO HIGHLIGHT:

- Great job you did setting up your Kanban board
- The tasks are split fairly 

Now you can merge this branch and move on :1st_place_medal: 
HAPPY CODING AND GOOD LUCK WITH THE COMMING ONES :crossed_fingers: :four_leaf_clover: 

![200w](https://user-images.githubusercontent.com/64173189/161605273-b83acc25-598e-4ec7-89d7-fde45a8f9338.gif)


Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._
